---
# tasks file for common
- name: Packages for all systems
  sudo: yes
  yum: "name='{{ item }}'"
  with_items: base_pkgs

- name: Custom Packages
  sudo: yes
  yum: "name='{{ item }}'"
  with_items: custom_pkgs